p = input("Escreva algo para saber tudo sobre: ")
print(f"O tipo primitivo é {type(p)}")
print(f"Ele esta todo em maisculo? {p.isupper()}")
print(f"Ele é alfanumerico? {p.isalnum()}")
print(f"Ele so contem texto? {p.isalpha()}")
print(f"Ele só contem numero? {p.isnumeric()}")
print(f"Ele esta so em letras minusculas? {p.islower()}")
print(f"É um numero decimal? {p.isdecimal()}")
print(f"Ele é um espaço? {p.isspace()}")
print(f"Esta capitalizado? {p.istitle()}")
print("End!")
